sculpin_content_types:
    posts:
        permalink: blog/:year/:month/:day/:filename/

sculpin_twig:
    source_view_paths:
        - _views
        - _layouts
        - _includes
        - _partials
        - ../.sculpin/puli/installer/src
